#!/bin/bash
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
QEMU="$SCRIPTPATH"/bin/qemu-system-loongarch64
SUDO=$(if [ $(whoami) = "root" ];then echo -n "";else echo -n "sudo";fi)
TFTP_DIR="$SCRIPTPATH"/../../easy-fs-fuse

OS="$SCRIPTPATH"/nand.dat
[ -e "$OS" ] || dd if=/dev/zero bs=1M count=$(((256*(2048+64)/2048)))|tr '\000' '\377' > "$OS"
BIOS="$SCRIPTPATH"/2k1000/u-boot-with-spl.bin
DEBUG_GMAC_PHYAD=0 "$QEMU" \
         -M ls2k -drive if=pflash,file=$BIOS \
         -m 1024 \
         -D $SCRIPTPATH/qemu.log \
         -serial stdio \
         -drive if=mtd,file="$OS" \
         -net nic -net user,net=192.168.1.2/24,tftp=$TFTP_DIR \
         -net nic -net user,net=10.0.3.0/24\
         -vnc 0.0.0.0:0 \
         -smp threads=1 \
         -hda $TFTP_DIR/rootfs-ubifs-ze.img \
         -s $@ 2>&1 \
         -k "$SCRIPTPATH"/share/qemu/keymaps/en-us

