#!/usr/bin/expect -f
set timeout -1
spawn {*}$argv
set bin_name [lindex $argv 0];

expect "Device(s) found"
send "ccccc\n"


expect "=>"
send "tftpboot uImage\n\n"


expect "Bytes transferred"
expect "=>"
send "bootm\n"

proc test_cmd {file_name num} {
    expect "\[1m\[32mNPUcore-IMPACT\[0m:\[1m\[34m/\[0m#"
    sleep $num
    send $file_name
}


# test_cmd "run-all.sh\n" 0
# test_cmd "busybox_testcode.sh\n" $sleep_time 
# test_cmd "lmbench_testcode.sh\n" $sleep_time 

interact