#!/usr/bin/expect -f
set timeout -1
spawn {*}$argv
set bin_name [lindex $argv 0];
expect "Device(s) found"
send "m"
expect "Device(s) found"
send "m"
expect "Press UP/DOWN to move, ENTER to select, ESC/CTRL+C to quit"
send "\033\[B\033\[B\r"

expect "Press UP/DOWN to move, ENTER to select"
if { $bin_name == "python3" } {
    sleep 20
}

send "\033\[B\r"
expect "update result: success"
expect "=>"
close
