#!/usr/bin/expect -f
# set qemu_bin [lindex $argv 0];
# set qemu_arg [lrange $argv 1 end];
set timeout -1
spawn {*}$argv
set bin_name [lindex $argv 0];
set sleep_time 0

proc test_cmd {file_name num} {
#    upvar 2 $sleep_time sleep_time
    expect "\[1m\[32mNPUCore\[0m:\[1m\[34m/\[0m#"
    sleep $num
    send $file_name
}

if  { $bin_name != "qemu-system-riscv64" } {
    expect "Device(s) found"
    send "mmmmmmmmmmmmmmmmmm"
    expect "Update kernel"
    send "\033\[B\r"


    expect "Press UP/DOWN to move, ENTER to select"

    if { $bin_name == "python3" || $bin_name == "python" } {
        set sleep_time 3
        sleep 20
    }

    send "\033\[B\r"
    expect "update result: success"
    send "bootm\n"
}

test_cmd "run-all.sh\n" $sleep_time 
# test_cmd "busybox_testcode.sh\n" $sleep_time 
# test_cmd "lmbench_testcode.sh\n" $sleep_time 

interact
